const dummyTexts = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nunc dui, porta eu arcu ac, sollicitudin tempor justo. Vestibulum eget lorem suscipit urna pulvinar finibus sit amet eu arcu. Integer venenatis augue risus, vel feugiat eros tristique et. Suspendisse sagittis ante dolor, id placerat diam pretium a. In et tortor ac nisi porttitor rhoncus. Suspendisse sed sapien nisi. Donec auctor lacinia tellus et pretium. Donec dignissim lacus libero, quis blandit felis laoreet eu. Aliquam quis dui vitae quam molestie fringilla vitae at dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tristique molestie nunc, nec accumsan odio accumsan id. Curabitur augue dolor, vestibulum dapibus feugiat eget, gravida at diam. In fermentum nulla quis auctor dapibus. Aliquam rutrum lorem non placerat cursus.',
  'Aliquam ultrices efficitur neque, elementum cursus neque interdum eu. Fusce viverra pellentesque convallis. Donec malesuada, nisi in commodo ornare, dolor nunc cursus ipsum, quis elementum nulla velit vitae nibh. Mauris blandit, lorem at accumsan facilisis, lectus neque sagittis quam, euismod sodales velit libero et arcu. Fusce auctor sapien sed auctor posuere. Suspendisse viverra laoreet rutrum. Phasellus purus metus, suscipit ac pellentesque in, auctor eget sapien.',
  'Maecenas bibendum tincidunt arcu eu sagittis. Integer iaculis tincidunt lorem, vel venenatis est lobortis quis. Etiam luctus tristique faucibus. In mattis nisi at ultrices tempor. Cras bibendum faucibus rutrum. Sed in ultrices dolor. Sed tristique tortor non tellus volutpat, ut rhoncus lectus accumsan. Duis eget libero tempus, interdum ante nec, viverra augue. Donec dui nunc, tempor vel nunc vitae, placerat consequat orci. Integer congue nec est et pharetra. Nunc quis accumsan nisl. Vestibulum quis massa eu turpis varius interdum eget non magna.',
  'Phasellus lobortis sem at blandit pharetra. Cras ac purus id nunc vehicula fringilla. Suspendisse ultricies tortor id quam pellentesque volutpat. Suspendisse potenti. Aliquam ut libero faucibus, placerat purus in, scelerisque tellus. Etiam eu ullamcorper risus. Sed pulvinar dui ut sem molestie sollicitudin in sed metus. Suspendisse imperdiet justo lacinia, venenatis tellus at, aliquet nulla. Maecenas lorem justo, mollis et molestie scelerisque, porttitor vestibulum libero. Maecenas nisi arcu, tristique at justo porta, vulputate pellentesque nunc. Etiam orci turpis, elementum id pulvinar et, lacinia at quam.',
  'Vestibulum a molestie erat. Suspendisse quis rutrum libero. Nulla consectetur, orci in finibus congue, purus enim hendrerit leo, non accumsan erat ipsum in magna. Etiam sit amet rhoncus neque. Vestibulum id mauris dignissim, egestas purus at, volutpat nibh. Suspendisse potenti. Etiam rutrum dui sed condimentum vulputate.',
  'Donec quis justo nisi. Integer suscipit lectus non risus tempus luctus. Sed sollicitudin enim magna, quis tincidunt dolor tincidunt et. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur pharetra aliquam volutpat. Donec tempor luctus ipsum id convallis. Nullam convallis lorem eu sodales dictum. Cras gravida nulla est, commodo molestie diam venenatis dapibus. Maecenas placerat ante dapibus justo eleifend, eu tincidunt elit rhoncus. Donec nec elit ante. Sed diam nisi, sagittis id imperdiet a, tincidunt sed nunc.',
]

export function genLoremIpsum(paragraphs = 1) {
  return dummyTexts.slice(0, paragraphs)
}
