name: Testing

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: npm install root
        run: npm i
        
      - name: npm install next
        run: |
          cd next
          npm i

      - name: run test
        run: npm run test
